name: Run Dockerized Banner App

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull shithi30/bannerapp:latest

    - name: Run Docker container
      run: docker run -e EMAIL_PASS=${{ secrets.EMAIL_PASS }} -e GCP_BLOB_KEY_JSON=${{ secrets.GCP_BLOB_KEY_JSON }} shithi30/bannerapp:latest
