name: Run Dockerized Application

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker image
      run: docker pull shithi30/myapp:latest

    - name: Run Docker container
      run: docker run -e SAMPLE_PASSWORD=${{ secrets.SAMPLE_PASSWORD }} shithi30/myapp:latest
